### PR TITLE
Automatic patching of auxClasspath

### PR DESCRIPTION
**Pull request by jakob-o**
We had some trouble with instrumentation and since we have no possibility to pass --auxClasspath per command line, I saw no other way than to do the patching in the instrumentation.

See:
 - https://github.com/cobertura/cobertura/wiki/FAQ#classnotfoundexception-during-instrumentation
 - https://github.com/cobertura/cobertura/issues/338
 - https://github.com/cobertura/cobertura/issues/231
  - https://github.com/cobertura/cobertura/issues/74
 - https://github.com/cobertura/cobertura/blob/db3bedf3334d8f35bad7ca3c6f4d777be6a09fc5/cobertura/src/main/java/net/sourceforge/cobertura/instrument/CoberturaClassWriter.java#L32

### CODE REVIEW

**Review by pawlakm — CHANGES_REQUESTED** [review]
Please address the following points:

1. please remove hardcoded ``maven-project`` dependency version. Instead, add in the parent pom.xml a ``<lib.version.maven-project>2.2.1</lib.version.maven-project>`` property to the ``properties``section and the following dependency in the ``dependencyManagement`` section :

```
      <dependency>
        <groupId>org.apache.maven</groupId>
        <artifactId>maven-project</artifactId>
        <version>${lib.version.maven-project}</version>
      </dependency>
```
2. please rename the ``patchAuxClasspath()`` to ``feedAuxClasspath``

3. please fix typo at line 202 : "No file fould" (should be "found")

Thanks in advance!

**Comment by pawlakm** [comment]
Again, thanks a lot for this PR and your time.

**Comment by jakob-o** [comment]
Thank you for creating the plugin!

**Review by pawlakm — APPROVED** [review]

**Comment by jmrozanec** [comment]
@jakob-o may we ask you to contribute this back to Cobertura? we will be glad to accept this fix for [issue 338](https://github.com/cobertura/cobertura/issues/338) as well as your issue #35 Thanks!

**Pull request merged**
